services:
  - type: web
    name: heartofthecards-api
    runtime: docker
    rootDir: CardAppBE
    dockerfilePath: ./Dockerfile
    branch: main
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
